### ISSUE TITLE
공통 컴포넌트 '모달' 

### ISSUE THREAD

**Issue by 0214kbs** [gamemuncheol/gamemuncheol-frontend#16]
### Goal
공통 모달 컴포넌트를 통해, 재사용 가능하도록 구현

### Requirements
- 디자이너가 제공한 스타일 가이드에 따라 모달 창 구현
- 화면의 정중앙에 배치하고 모달을 제외한 뒷 배경 어둡게 처리
- 매개변수를 통해 타이틀, 내용 및 버튼 등을 동적으로 조정할 수 있도록 구현

### Todo  
- [x] 모달 창 기본 레이아웃 구현 (제목, 소제목, 닫기, 내용 영역, 선택적 하단 버튼)
- [x] 디자인 가이드에 맞춰 스타일 구현
- [x] 모달 열고 닫는 기능
